export const IMAGES = {
    // voucher: 'https://uploadthingy.s3.us-west-1.amazonaws.com/uwPYNNRiavmZZ285SkzD5Z/diaomnd.png',
    voucher: '/ti 59.png',
    diamond: 'https://uploadthingy.s3.us-west-1.amazonaws.com/agrcZVSRX593jbti3xzVTM/heart.png',
    coin: 'https://uploadthingy.s3.us-west-1.amazonaws.com/2XiBYwBWgNJxytH6Z2jPWP/point.png',
    ticket: 'https://uploadthingy.s3.us-west-1.amazonaws.com/65WCbcmf6dyyeqvjSAJHyp/fire.png',
    cookyFlip: '/CookyFlip.png',
    logo: 'https://uploadthingy.s3.us-west-1.amazonaws.com/uYsqLmRkx6f1zBGRqMZA6G/cookycreanlogo3.png',
    fortuneCooky: '/fortuneCooky.png',
    badCooky: '/badCooky.png',
    freeFlip: '/freeFlip.png',
    grandWin: '/PricingWrapper.png',
    outOfStock: '/outofstock.png',
    crackedCooky: '/crackedcook.png',
    antsInTheJar: '/ant.png',
};
